---
deployment:
  tasks:
    - export DEPLOYPATH=/home/sylcdvaa/public_html/
    # Delete old files first
    - /bin/rm -rf $DEPLOYPATH/static
    - /bin/rm -f $DEPLOYPATH/index.html
    - /bin/rm -f $DEPLOYPATH/asset-manifest.json
    - /bin/rm -f $DEPLOYPATH/favicon.ico
    # Copy new build files individually
    - /bin/cp -f build/index.html $DEPLOYPATH/index.html
    - /bin/cp -f build/asset-manifest.json $DEPLOYPATH/asset-manifest.json
    - /bin/cp -f build/favicon.ico $DEPLOYPATH/favicon.ico
    # Copy static directory recursively
    - /bin/cp -R build/static $DEPLOYPATH/
    # Copy .htaccess for React Router
    - /bin/cp -f .htaccess $DEPLOYPATH/.htaccess
    # Copy test file
    - /bin/cp -f test.html $DEPLOYPATH/test.html
    # Set permissions
    - /bin/chmod 644 $DEPLOYPATH/index.html
    - /bin/chmod 644 $DEPLOYPATH/asset-manifest.json
    - /bin/chmod 644 $DEPLOYPATH/.htaccess
    - /bin/chmod -R 755 $DEPLOYPATH/static
